### PR TITLE
Pin notes

### PR DESCRIPTION
**Pull request by gonzalovelasco**
Screenshot 2023-09-07 at 15 10 26

### CODE REVIEW

**Review by matthewwong525 — CHANGES_REQUESTED** [review]
Thank you for quickly putting together something! I didn't clarify this in my ticket request but can you add the pin button beside the notes selected toolbar. See below:
image

I do not want the pinned icon here:
image

that being said, great work! you layed a lot of the ground work with minimal supervision now it's just small changes. I'm happy and very impressed

**Comment by gonzalovelasco** [comment]
> Thank you for quickly putting together something! I didn't clarify this in my ticket request but can you add the pin button beside the notes selected toolbar. See below: image
> 
> I do not want the pinned icon here: image
> 
> that being said, great work! you layed a lot of the ground work with minimal supervision now it's just small changes. I'm happy and very impressed



Screenshot 2023-09-11 at 18 05 01
Screenshot 2023-09-11 at 18 05 11

**Review by matthewwong525 — CHANGES_REQUESTED** [review]
Deleting with pinned notes doesn't work. When a note is deleted, it doesn't delete the pinned note as well. Please add test for this as well!

**Comment by gonzalovelasco** [comment]
> Deleting with pinned notes doesn't work. When a note is deleted, it doesn't delete the pinned note as well. Please add test for this as well!

Fixed 847fff81d5312aa44b6e1848b345e598b9fd1d50

**Pull request merged**
