### PR TITLE
Fix data loss android

### PR DESCRIPTION
**Pull request by gonzalovelasco**

### CODE REVIEW

**Comment by matthewwong525** [comment]
I think the new notes not being saved is a feature. what problem is this trying to solve @gonzalovelasco ?

**Comment by matthewwong525** [comment]
There's a cache and we want to save the note to the cache and then when I open a new note then it'll save the cache into the "database"

**Comment by gonzalovelasco** [comment]
> There's a cache and we want to save the note to the cache and then when I open a new note then it'll save the cache into the "database"

Save the cached note before opening a new one fe2ec9faa33bff414723ad926711d382b6fd5825

**Review by matthewwong525 — APPROVED** [review]
Look at the changes i made and lmk if you think it's ok. then merge: https://github.com/fleetingnotes/fleeting-notes-flutter/pull/927/commits/ddd39b79df6d96a802b82f8d1dd93ef36bcc26df

**Comment by gonzalovelasco** [comment]
LGTM

**Pull request merged**
